### ISSUE TITLE
Missing Methods ?

### ISSUE THREAD

**Issue by nebiljabari** [menpo/conda-opencv3#11]
First of all thank you menpo for this convenient package.
After 2 days of Googling, experimenting, build and re-build (with opencv + opencv_contrib) I post this issue

It appears to me that the install is missing (or can't reach ?) some class and/or methods Iam right ?
For exemple when I do : 

```
>>> dir(cv2.face)
['MinDistancePredictCollector', 'MinDistancePredictCollector_create', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'createEigenFaceRecognizer', 'createFisherFaceRecognizer', 'createLBPHFaceRecognizer']
```

I don't see `FaceRecognizer`, `BasicFaceRecognizer`, `PredictCollector` or `StandardCollector` 
_(but they are present in the root folder : `include/opencv2/face/`)_ 
is it normal or am I missing something ?

To be more specific,
I try to obtain the `confidence` score of the `predict()` method coming from : `cv2.face.createLBPHFaceRecognizer()` but I only obtain the label output. 
Some research on the [openCV doc](http://docs.opencv.org/trunk/dd/d65/classcv_1_1face_1_1FaceRecognizer.html) showed me that I have to enter in the arguments a `collector` coming from `cv2.face.PredictCollector()` 
but when I try that : `AttributeError: module 'cv2.face' has no attribute 'PredictCollector'`

@patricksnape I've [read](https://github.com/menpo/conda-opencv3/issues/5) you use the face detection module. Maybe a little help ? Thanks

**Comment by nebiljabari** [comment]
I think Ive discover where the problem come from. It's a [logic bug](https://github.com/opencv/opencv_contrib/issues/512) present in the face.hpp file who have been debug since. Is there a way to make an update or to indicate me how to fix that on my machine ?

**Comment by patricksnape** [comment]
This is a bug with the OpenCV contrib package - this repository simply creates a Python build of OpenCV + the contrib packages. Unfortunately, there hasn't been a new release of OpenCV for some time and thus you will need to pressure the OpenCV developers to make a 3.2 release. I am not able to provide builds of unreleased OpenCV versions.
