### ISSUE TITLE
"conda build conda" fails with error "cannot find hdf5.h" and build is pointing to a scrambled path like " _b_env_placehold_placehold_placehold_placehold.... goes on"

### ISSUE THREAD

**Issue by VishnuMadhu** [menpo/conda-opencv3#15]
I am pretty new to conda builds , please forgive my lack of knowledge
I wonder why no one has reported this issue.
For me conda build conda fails at 98% . Probable cause is some wrong headers included in modules/hdf/include/opencv2/hdf/hdf5.hpp .

But this issue seems to be already closed in the opencv - master long time back [Fix: public hdf headers](https://github.com/opencv/opencv_contrib/pull/532/files)
On inspecting meta.yaml , I could see an opencv archive getting downloaded . 

Can we change this archive to point to something new and do conda build ? Please provide suggestions for a successful build

**Comment by patricksnape** [comment]
The placeholder is expected conda behaviour - it has to do with inserting the maximum path possible so that relocatable binaries are created.

I obviously built the code here and uploaded it and didn't see the issue you are describing - so it's likely that your setup is slightly different than mine. In terms of a 'newer' version of OpenCV, 3.2.0 was just released but I haven't had time to invest in creating a working build for it yet (as this is a very time consuming effort) - see #14.

**Comment by VishnuMadhu** [comment]
Patrick , appreciate the quick response.
Apparently opencv-contrib tag 3.1.0 referenced by conda build is having the issue.

Do you have any docs that i can refer for making conda-recipe for opencv

**Comment by patricksnape** [comment]
You may have some luck setting this:

```
export CFLAGS="$CFLAGS -I$PREFIX/include"
export CXXFLAGS="$CXXFLAGS -I$PREFIX/include"
```

before running the CMake command?

**Comment by gauravpandeyamu** [comment]
@VishnuMadhu I am facing a similar problem. Were you able to resolve the issue?

**Comment by magsol** [comment]
Same; hdf5 is referenced in the `meta.yaml` file under both build and run dependencies, but for some reason is nonetheless failing around 98% build progress for OpenCV. 

Though I did notice in the initial conda environment setup, before the `build.sh` script is invoked:

    user@server:~/conda-opencv3$ conda build conda/
    BUILD START: opencv3-3.1.0-py35_0
    updating index in: /conda/conda-bld/linux-64
    updating index in: /conda/conda-bld/noarch

    The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                  conda-forge
    bzip2:           1.0.6-0                       conda-forge
    ca-certificates: 2017.1.23-0                   conda-forge
    certifi:         2017.1.23-py35_0              conda-forge
    cmake:           3.7.1-4                       conda-forge
    curl:            7.52.1-0                      conda-forge
    eigen:           3.2.7-0                       menpo      
    expat:           2.1.0-2                       conda-forge
    jsoncpp:         0.10.6-1                      conda-forge
    libarchive:      3.2.1-2                       conda-forge
    libgfortran:     3.0.0-1                                  
    libiconv:        1.14-4                        conda-forge
    libuv:           1.11.0-0                      conda-forge
    ncurses:         5.9-10                        conda-forge
    numpy:           1.12.1-py35_blas_openblas_200 conda-forge [blas_openblas]
    openblas:        0.2.19-1                      conda-forge
    openssl:         1.0.2h-3                      conda-forge
    pip:             9.0.1-py35_0                  conda-forge
    python:          3.5.3-1                       conda-forge
    readline:        6.2-0                         conda-forge
    setuptools:      33.1.1-py35_0                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.19-1                      conda-forge
    wheel:           0.29.0-py35_0                 conda-forge
    xz:              5.2.2-0                       conda-forge
    zlib:            1.2.11-0                      conda-forge

there's no mention of hdf5 anywhere in that list of installed packages.

**Comment by patricksnape** [comment]
Please use the [conda-forge opencv](https://github.com/conda-forge/opencv-feedstock) where I just pushed a new build for OpenCV 3.2.0 (wait an hour or two for it to be uploaded)

**Comment by magsol** [comment]
oooOOOoooo, thank you, will do!

**Comment by remoteblue** [comment]
@patricksnape , it works. Thanks!
