### ISSUE TITLE
Unable to "import cv2" after building opencv with conda-build

### ISSUE THREAD

**Issue by paramrajpura** [menpo/conda-opencv3#28]
After successfully building OpenCV 3.1 for ubuntu 14.04 as instructed in readme by editing build.sh with FFMPEG=1, 
at the end I encounter error in "run_test.py" as it cannot import cv2.

I checked the _t_env created, the python3.6/site-packages/ doesn't have cv2 files. Though I see other libopencv.so files in '"/_t_env/lib" folder.
What can be the reason behind this issue?

**Comment by remoteblue** [comment]
You may want to do 
$python
>>> import cv2
If it returns error, then check ~/.bashrc to see whether $PATH and $PYTHONPATH is appropriate.

Try this: http://stackoverflow.com/questions/42562876/opencv3-error-unable-to-stop-the-stream-inappropriate-ioctl-for-device?noredirect=1#comment73361334_42562876

**Comment by patricksnape** [comment]
Please use the conda-forge OpenCV which will soon be built with FFMPEG

**Comment by paramrajpura** [comment]
Thank you @remoteblue and @patricksnape .

Got the opencv with ffmpeg working from conda-forge/opencv-feedstock !!!
