### ISSUE TITLE
OpenCV 3.0.0

### ISSUE THREAD

**Issue by jlaura** [menpo/conda-opencv3#5]
First, thanks for serving these via binstar - immensely helpful to all of us.  The upgrade to 3.1.0 causes breakage in the Python API for the [Flann Matcher](https://github.com/Itseez/opencv/issues/5667).  

Seeing this, I forked your project and rolled back to the last commit before the 3.1.0 upgrade.  Builds are successful via Travis (Linux) and a local OS X install (10.11.1).  I am though seeing an intermittent memory related error using the Flann Matcher in 3.0.0 (specifically when adding descriptors).  This is not something I saw in your original builds.

Is this something that you encountered and patched?

Is your 3.0.0 build replaced by the 3.1.0 build on binstar?  I assume so, but figured I would ask.

**Comment by patricksnape** [comment]
Oh darn! 

I'm very sorry about that - this puts me in a bit of a bind. I honestly have just been building these for the sake of the community and I don't extensively use OpenCV outside of the face detection module. I also don't run an exhaustive test suite on these builds as I have been assuming that the tagged releases from OpenCV don't contain any breaking bugs - looks like I am wrong!

The biggest issue is that (unfortunately) my free account on binstar/anaconda only allows 2GB of file space and these OpenCV 3.x builds take ~1GB _per version_. So I had to delete the 3.0 build just to fit the 3.1 build on my account. Normally I would prefer to keep all versions I build, but I simply can't on the Anaconda free tier.

[This commit](https://github.com/menpo/conda-opencv3/commit/f1147b9958d250c2a90ede01366a3a48e44a1013) should be the last commit that actually works - before I started messing around with Python 3.5 support. Is this commit still broken? Are you seeing the errors on both Linux and OSX?

**Comment by jlaura** [comment]
I will give that commit a go and see if I can get a clean build.  If so, I am glad to host openCV 3.0.0 on my binstar account and will serve for all 3 platforms.  Hopefully the OpenCV team is able to address the 3.1.0 binding bug at somepoint in the near future (though it does not sound like a high priority yet).

**Comment by jlaura** [comment]
@patricksnape Here are [travis builds](https://travis-ci.org/USGS-Astrogeology/conda-opencv3/builds/104121460) for both Linux and OS X.  I did bump a few commits ahead to get Python 3.5 support.  The files are available via [binstar](https://anaconda.org/jlaura/OpenCV3/files).  I am still seeing the intermittent memory issue.  

If you have a moment, does anything look out of sorts with those builds?  I see a few warnings, but no errors.

**Comment by jlaura** [comment]
I think I found the issue.  The openCV3.0.0 release happened June 3. [This PR](https://github.com/Itseez/opencv/pull/4111), that looks like it will fix the issue was merged June 10.  I am going to try altering the git clone in the .travis.yml to see if I can rollback to this PR.

**Comment by jlaura** [comment]
Success.  Thanks for the info!  The 3.0.0 release with Python 3.5 support is now available via my binstar.
https://anaconda.org/jlaura/opencv3
https://travis-ci.org/USGS-Astrogeology/conda-opencv3

**Comment by patricksnape** [comment]
Great - glad to hear it! Though that bug does appear to be in 3.1 and I was also seeing segmentation faults on my OSX build even going back to 3.0 :confused:. I tried to git bisect but its super difficult to bisect and keep in sink both opencv_contrib **and** opencv. Since they need to be in sync but only the actual tagged releases have any guarantee of working together!

Unfortunately this FLANN matcher bug needs SIFT or SURF so contrib is required - which is frustrating.
