### ISSUE TITLE
Install conda-opencv3 on Mac osx-64

### ISSUE THREAD

**Issue by tofighi** [menpo/conda-opencv3#6]
conda install -c https://conda.anaconda.org/tofighi opencv3

**Comment by patricksnape** [comment]
I'm confused as to what the issue is here? I already provide packages for all operating systems (excluding linux-32) on the menpo channel.

**Comment by tofighi** [comment]
@patricksnape sorry patrick. I just created the file and share for others. I didn't know you made it before.
Thanks

**Comment by patricksnape** [comment]
Ah right! Thanks for hosting the build - glad you got it to work! That's a good sign!
