### ISSUE TITLE
No binding for function cv::EMD

### ISSUE THREAD

**Issue by juhka** [menpo/conda-opencv3#7]
I installed the package with conda (win-64/opencv3-3.1.0-py34_0.tar.bz2) and noticed that there is no binding for the function `cv::EMD`. I assume it should be `cv2.EMD` in Python. Other image processing functions such as `cv2.CalcHist` are available. Is this functionality disabled on purpose or is there some other issue?

**Comment by patricksnape** [comment]
If [the documentation](http://docs.opencv.org/3.0-beta/modules/imgproc/doc/histograms.html) is anything to go by it appears that the EMD is not exposed to Python? This appears to be an issue with the OpenCV3 project itself. If I am wrong then let me know and point me to a resource that explains how to use EMD in Python in OpenCV3 and I will update the build!

**Comment by juhka** [comment]
Thanks for your response. I am new to OpenCV, but it seems to be an issue with OpenCV3 itself, and I will raise it in that project. In the meanwhile, the function is available from OpenCV2 package.

I came across [the same question](http://answers.opencv.org/question/73184/opencv-30-python-replacement-for-calcemd2/) in the OpenCV forums, but no answer there.
