### ISSUE TITLE
Does conda-opencv3 support the use of the text module 

### ISSUE THREAD

**Issue by mobcdi** [menpo/conda-opencv3#9]
Or is that a silly question because the text module hasn't been made available in Python yet?

[http://docs.opencv.org/3.0-beta/modules/text/doc/text.html](http://docs.opencv.org/3.0-beta/modules/text/doc/text.html)

**Comment by patricksnape** [comment]
Unfortunately it looks as though that functionality has not beed exposed in Python yet. If you are using the C++ and find that this is missing then please advise on the appropriate build flags and I can always update the build.
